version: '3.5'
services:
  # API
  foodlord-api-app:
    image: foodlord-api-app
    container_name: foodlord-api-app
    env_file:
      - api/.env
    build:
      context: api
      dockerfile: Dockerfile
    networks:
      - foodlord
    ports:
      - 9081:9081
      - 3081:3081
    restart: always
    depends_on:
      - foodlord-api-nginx
  foodlord-api-nginx:
    image: foodlord-api-nginx
    container_name: foodlord-api-nginx
    build:
      context: api
      dockerfile: Dockerfile.nginx
    networks:
      - foodlord
    ports:
      - 8081:8081
    restart: always

  # Client
  foodlord-client-app:
    container_name: foodlord-client-app
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 80:3000
    environment:
      - NODE_ENV=development
    restart: always

  # DB
  foodlord-db:
    image: foodlord-db
    container_name: foodlord-db
    build:
      context: db
      dockerfile: Dockerfile
    restart: always
    networks:
      - foodlord
    ports:
      - 5432:5432

# FoodLord network
networks:
  foodlord:
    name: foodlord
    driver: bridge